CoffeeCat/CoffeeCatRazporPage/Pages/Staff/StaffHomePage.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using NuGet.Protocol.Core.Types;
using Repositories;
using Repositories.Auth;

namespace CoffeeCatRazporPage.Pages.Staff {
    public class StaffHomePageModel : PageModel {
        private readonly ICoffeeShopStaffRepository _cofffeeShopStaffRepository;
        private readonly ISessionRepository sessionrepository;
        public StaffHomePageModel(ICoffeeShopStaffRepository cofffeeShopStaffRepository ,ISessionRepository sessionrepository) 
        {
            _cofffeeShopStaffRepository = cofffeeShopStaffRepository;
            this.sessionrepository = sessionrepository;
        }
        [BindProperty(SupportsGet = true)]
        public List<Booking> Bookings { get; set; }
        public async Task OnGet() {
            Authenticate();
            Authorization();
            var staff =  sessionrepository.GetUserByRole( HttpContext.Session.GetInt32("UserId"));
            Bookings = await _cofffeeShopStaffRepository.GetBookingsByShopIdAsync(staff.ShopId);
        }
        public async Task<IActionResult> OnPostConfirmBookingAsync(int id)
        {
            var booking = await _cofffeeShopStaffRepository.GetBookingByIdAsync(id);

            booking.BookingEnabled = true;
            await _cofffeeShopStaffRepository.UpdateAsync(booking);

            return RedirectToPage();
        }
        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 3) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Staff/StaffHomePage.cshtml
@page
@model CoffeeCatRazporPage.Pages.Staff.StaffHomePageModel
@{
    ViewData["Title"] = "Booking Manager";
}

<h1>@ViewData["Title"]</h1>

<div class="table-responsive">
    <table class="table table-striped table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Booking ID</th>
                <th>Booking Code</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Customer Name</th>
                <th>Tables</th>
                <th>Items</th>
                <th>Confirm</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var booking in Model.Bookings)
            {
                <tr>
                    <td>@booking.BookingId</td>
                    <td>@booking.BookingCode</td>
                    <td>@booking.BookingStartTime</td>
                    <td>@booking.BookingEndTime</td>
                    <td>@booking.Customer.CustomerName</td>
                    <td>
                        @foreach (var table in booking.Tables)
                        {
                            <span class="badge badge-light text-dark">@table.TableName</span>
                            <br />
                        }
                    </td>
                    <td>
                        @foreach (var item in booking.Items)
                        {
                            <span class="badge badge-light text-dark">@item.ItemName</span>
                            <br />
                        }
                    </td>
                    <td>@booking.BookingEnabled</td>
                    <td>
                            @if (!booking.BookingEnabled ?? false)
                            {
                            <form method="post" asp-page-handler="ConfirmBooking" asp-route-id="@booking.BookingId">
                                <button type="submit" class="btn btn-success">Confirm</button>
                            </form>
                            }
                    </td>
                                    
                </tr>
            }
        </tbody>
    </table>
</div>