CoffeeCat/CoffeeCatRazporPage/Pages/Admin/Create.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories.Admin;
using Repositories.Auth;

namespace CoffeeCatRazporPage.Pages.Admin {
    [BindProperties]
    public class CreateModel : PageModel {
        private readonly IAdminRepository _adminRepository;
        private readonly ISessionRepository _sessionRepository;

        public User User { get; set; }
        public Shop Shop { get; set; }

        public CreateModel(IAdminRepository adminRepository, ISessionRepository sessionRepository) {
            _adminRepository = adminRepository;
            _sessionRepository = sessionRepository;
            User = new User();
            Shop = new Shop();
        }
        public void OnGet() {
            Authenticate();
            Authorization();
        }

        public async Task<IActionResult> OnPost() {
            if (!ModelState.IsValid) {
                return Page();
            }
            User.Shop = Shop;
            User.RoleId = 2;
            await _adminRepository.CreateShopOwner(User);
            return RedirectToPage("/Admin/Admin");
        }

        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 1) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Home/ShopOwner.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoffeeCatRazporPage.Pages.Home
{
    public class ShopOwnerModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/AreaManager.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Repositories;
using Repositories.Auth;

namespace CoffeeCatRazporPage.Pages.ShopOwner {
    public class AreaManagerModel : PageModel {
        private readonly ICoffeeShopManagerRepository<Area> repository;
        private readonly ISessionRepository sessionrepository;
        public AreaManagerModel(ICoffeeShopManagerRepository<Area> repository, ISessionRepository sessionrepository) {
            this.repository = repository;
            this.sessionrepository = sessionrepository;
        }

        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        public IEnumerable<Area> Areas { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int ShopId { get; set; }
        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; } = 1;

        [BindProperty(SupportsGet = true)]
        public string SortOrder { get; set; }



        public async Task OnGetAsync(int? pageIndex, string sortOrder, int shopId) {
            Authenticate();
            Authorization();
            var shopOwner = sessionrepository.GetUserByRole( HttpContext.Session.GetInt32("UserId"));
            IQueryable<Area> areasQuery = await repository.GetAreasByShopIdAsync(shopOwner.ShopId);
            ShopId = shopId;
            // Tìm kiếm
            if (!string.IsNullOrEmpty(SearchString)) {
                areasQuery = areasQuery.Where(s => s.AreaName.Contains(SearchString));
            }

            // Sắp xếp
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AddressSortParm"] = sortOrder == "Address" ? "address_desc" : "Address";

            switch (sortOrder) {

                case "Address":
                    areasQuery = areasQuery.OrderBy(s => s.AreaId);
                    break;
                case "address_desc":
                    areasQuery = areasQuery.OrderByDescending(s => s.AreaId);
                    break;

            }

            // Phân trang
            int pageSize = 5;
            CurrentPage = pageIndex ?? 1;
            TotalPages = (int)Math.Ceiling(await areasQuery.CountAsync() / (double)pageSize);

            Areas = await areasQuery.Skip((CurrentPage - 1) * pageSize).Take(pageSize).ToListAsync();

        }

        public async Task<IActionResult> OnPostToggleEnabledAsync(int id, bool isEnabled) {
            var area = await repository.GetAreaByIdAsync(id);

            if (area == null) {
                return NotFound();
            }

            area.AreaEnabled = isEnabled;
            await repository.UpdateAsync(area);

            return RedirectToPage(new { shopId = area.ShopId, pageIndex = PageIndex });
        }

        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 2) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/Catmanager.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Repositories;

namespace CoffeeCatRazporPage.Pages.ShopOwner {
    public class CatmanagerModel : PageModel {
        private readonly ICoffeeShopManagerRepository<Cat> repository;

        public CatmanagerModel(ICoffeeShopManagerRepository<Cat> repository) {
            this.repository = repository;
        }

        [BindProperty(SupportsGet = true)]
        public string SearchString { get; set; }

        public IEnumerable<Cat> Cats { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int AreaId { get; set; }
        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; } = 1;

        [BindProperty(SupportsGet = true)]
        public string SortOrder { get; set; }

        public async Task OnGetAsync(int? pageIndex, string sortOrder, int areaId) {
            Authenticate();
            Authorization();
         
            IQueryable<Cat> catsQuery = await repository.GetCatsByAreaIdAsync(areaId);
            AreaId = areaId;
          
            if (!string.IsNullOrEmpty(SearchString)) {
                catsQuery = catsQuery.Where(s => s.CatName.Contains(SearchString));
            }

         
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["AddressSortParm"] = sortOrder == "Address" ? "address_desc" : "Address";

            switch (sortOrder) {
                case "name_desc":
                    catsQuery = catsQuery.OrderByDescending(s => s.CatName);
                    break;
                case "Address":
                    catsQuery = catsQuery.OrderBy(s => s.CatId);
                    break;
                case "address_desc":
                    catsQuery = catsQuery.OrderByDescending(s => s.CatId);
                    break;
                default:
                    catsQuery = catsQuery.OrderBy(s => s.CatName);
                    break;
            }

            // Phân trang
            int pageSize = 5;
            CurrentPage = pageIndex ?? 1;
            TotalPages = (int)Math.Ceiling(await catsQuery.CountAsync() / (double)pageSize);

            Cats = await catsQuery.Skip((CurrentPage - 1) * pageSize).Take(pageSize).ToListAsync();
        }

        public async Task<IActionResult> OnPostToggleEnabledAsync(int id, bool isEnabled) {
            var cat = await repository.GetCatByIdAsync(id);

            if (cat == null) {
                return NotFound();
            }

            cat.CatEnabled = isEnabled;
            await repository.UpdateAsync(cat);

            return RedirectToPage(new { areaId = cat.AreaId, pageIndex = PageIndex });
        }

        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 2) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/CreateArea.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories;
using Repositories.Auth;

namespace CoffeeCatRazporPage.Pages.ShopOwner {
    public class CreateAreaModel : PageModel {
        private readonly ICoffeeShopManagerRepository<Shop> shopRepository;
        private readonly ICoffeeShopManagerRepository<Area> areaRepository;
        private readonly ISessionRepository sessionrepository;
        public CreateAreaModel(ICoffeeShopManagerRepository<Shop> shopRepository, ICoffeeShopManagerRepository<Area> areaRepository, ISessionRepository sessionrepository) {
            this.shopRepository = shopRepository;
            this.areaRepository = areaRepository;
            this.sessionrepository = sessionrepository;
            Areas = new List<Area>();
        }

        [BindProperty]
        public Shop shop { get; set; }
        [BindProperty]
        public Area area { get; set; }
        public List<Area> Areas { get; set; }
        public string ErrorMessage { get; set; }
        public async Task<IActionResult> OnGetAsync() {
            Authenticate();
            Authorization();
            var shopOwner = sessionrepository.GetUserByRole( HttpContext.Session.GetInt32("UserId"));
            Areas = await areaRepository.GetAreaByShopIdAsync(shopOwner.ShopId);

            area = await areaRepository.GetAreaByIdAsync(shopOwner.ShopId);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (string.IsNullOrEmpty(area.AreaName))
            {
                ErrorMessage = "Area name cannot be empty.";
                return Page();
            }

            var shopOwner = sessionrepository.GetUserByRole( HttpContext.Session.GetInt32("UserId"));
            var existingArea = await areaRepository.GetAreaByNameAsync(area.AreaName, shopOwner.ShopId);
            if (existingArea != null)
            {
                ErrorMessage = "Area name already exists in this shop.";
                return Page();
            }

            area.AreaEnabled = true;
            area.ShopId = shopOwner.ShopId;
            await areaRepository.AddAsync(area);

            return RedirectToPage("./AreaManager", new { shopId = area.ShopId, pageIndex = 1 });
        }


        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 2) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/CreateCat.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories;

namespace CoffeeCatRazporPage.Pages.ShopOwner {
    public class CreateCatModel : PageModel {
        private readonly ICoffeeShopManagerRepository<Cat> catRepository;
        private readonly ICoffeeShopManagerRepository<Area> areaRepository;

        public CreateCatModel(ICoffeeShopManagerRepository<Cat> catRepository, ICoffeeShopManagerRepository<Area> areaRepository) {
            this.catRepository = catRepository;
            this.areaRepository = areaRepository;
            Cats = new List<Cat>();
        }

        [BindProperty]
        public Area area { get; set; }
        [BindProperty]
        public Cat Cat { get; set; }
        public List<Cat> Cats { get; set; }
        public string ErrorMessage { get; set; }
        public async Task<IActionResult> OnGetAsync(int areaId) {
            Authenticate();
            Authorization();

            Cats = await catRepository.GetCatByAreaIdAsync(areaId);

            area = await areaRepository.GetAreaByIdAsync(areaId);

            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
           

          
            var existingCat = await catRepository.GetCatByNameAsync(Cat.CatName, area.AreaId);
            if (existingCat != null)
            {
                ErrorMessage = " cat name already exists in this area.";
                return Page();
            }
           

            if (string.IsNullOrWhiteSpace(Cat.CatName))
            {
                ErrorMessage = "cat name cannot be empty.";
                return Page();
            }
            Cat.CatEnabled = true;
            await catRepository.AddAsync(Cat);

            return RedirectToPage("./CatManager", new { areaId = area.AreaId, pageIndex = 1 });
        }

        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 2) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/StaffManager.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories;

namespace CoffeeCatRazporPage.Pages.ShopOwner
{
    public class StaffManagerModel : PageModel
    {
        private readonly ICoffeeShopStaffRepository _staffRepository;
        public StaffManagerModel(ICoffeeShopStaffRepository coffeeShopStaffRepository)
        {
            _staffRepository = coffeeShopStaffRepository;
        }
        public List<User> UserList { get; set; }
        public async Task OnGetAsync(int roleId)

        {
            Authenticate();
            /*  Authorization();*/
            /* int roleId2ShopId = await _staffRepository.GetShopIdByRoleId(2);
             UserList = await _staffRepository.GetUsersByRoleIdAndShopId(3, roleId2ShopId);*/

            /*UserList = await _staffRepository.GetUserbyRold(3);*/
            int? ownerId = HttpContext.Session.GetInt32("OwnerId");
            if (ownerId != null)
            {
                int? shopId = await _staffRepository.GetShopIdByOwnerId(ownerId.Value);
                if (shopId != null)
                {
                    UserList = await _staffRepository.GetStaffByShopId(shopId.Value);
                }
            }
        }
        public async Task<IActionResult> OnPostBanAsync(int customerId)
        {
            await _staffRepository.Ban(customerId);
            return RedirectToPage("/ShopOwner/StaffManager");
        }

        public async Task<IActionResult> OnPostUnbanAsync(int customerId)
        {
            await _staffRepository.Unban(customerId);
            return RedirectToPage("/ShopOwner/StaffManager");
        }
        private void Authenticate()
        {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null)
            {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

    /*    private void Authorization()
        {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue)
            {
                if (roleId.Value != 1)
                {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }*/
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/AreaManager.cshtml
@page
@model AreaManagerModel
@{
    ViewData["Title"] = "Area Manager";
}
<div class="container">
    <h1 class="text-center my-4">Area Manager</h1>

    <!-- Sắp xếp và Tạo mới -->
    <div class="d-flex justify-content-between my-3">
        <div>
            <a asp-page-handler="Sort" asp-route-sortOrder="Address" class="btn btn-link mx-2">Sort </a>
        </div>
        <div>
            
            <a asp-page="CreateArea" asp-route-shopId="@Model.ShopId" class="btn btn-primary">Create New Area</a>
        </div>
    </div>

    <!-- Tìm kiếm -->
    <form method="get" class="mb-4">
        <div class="input-group">
            <input type="text" name="searchString" class="form-control" placeholder="Search">
           
            <input type="hidden" name="sortOrder" value="@ViewData["CurrentSort"]" />
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Enabled</th>
                <th>Manage</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var area in Model.Areas)
            {
                <tr>
                    <td>@area.AreaId</td>
                    <td>@area.AreaName</td>             
                    <td>@(area.AreaEnabled ?? false)</td>
                    <td>
                        <div>
                            <a asp-page="CatManager" asp-route-areaId="@area.AreaId">Manage Cat</a>
                            <br />
                            <a asp-page="TableManager" asp-route-areaId="@area.AreaId">Manage Table</a>
                        </div>
                    </td>
                    <td>
                        <form method="post" asp-page-handler="ToggleEnabled" asp-route-id="@area.AreaId" asp-route-isEnabled="@(!area.AreaEnabled)">
                            <button type="submit" class="btn btn-link">@((area.AreaEnabled ?? false) ? "Disable" : "Enable")</button>
                        </form>
                        <!-- Nút Update -->
                        <a asp-page="UpdateArea" asp-route-shopId="@area.ShopId " asp-route-id="@area.AreaId" class="btn btn-link">Update</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-page="./ShopManager" class="btn btn-primary">Back</a>
    <!-- Phân trang -->
    <div class="d-flex justify-content-center my-3">
        @if (Model.TotalPages > 1)
        {
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    @for (var i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                            <a class="page-link" asp-page="./AreaManager" asp-route-pageIndex="@i" asp-route-shopId="@Model.ShopId">@i</a>
                        </li>
                    }
                </ul>
            </nav>
        }
    </div>

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/Catmanager.cshtml
@page
@model CatmanagerModel
@{
    ViewData["Title"] = "Cat Manager";
}

<div class="container">
    <h1 class="text-center my-4">Cat Manager</h1>

    <!-- Sắp xếp và Tạo mới -->
    <div class="d-flex justify-content-between my-3">
        
        <div>

            <a asp-page="CreateCat" asp-route-areaId="@Model.AreaId" class="btn btn-primary">Create New Cat</a>
        </div>
    </div>



    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Image</th>
                <th>Enabled</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cat in Model.Cats)
            {
                <tr>
                    <td>@cat.CatId</td>
                    <td>@cat.CatName</td>
                    <td>
                        <img src="@cat.CatImage" alt="Cat Image" style="max-width: 100px; max-height: 100px;" />
                    </td>
                    <td>@(cat.CatEnabled ?? false)</td>
                    <td>
                        <form method="post" asp-page-handler="ToggleEnabled" asp-route-id="@cat.CatId" asp-route-isEnabled="@(!cat.CatEnabled)">
                            <button type="submit" class="btn btn-link">@((cat.CatEnabled ?? false) ? "Disable" : "Enable")</button>
                        </form>
                        <!-- Nút Update -->
                        <a asp-page="UpdateCat" asp-route-areaId="@cat.AreaId "asp-route-id="@cat.CatId" class="btn btn-link">Update</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-page="./AreaManager" class="btn btn-primary">Back</a>
    <!-- Phân trang -->
    <div class="d-flex justify-content-center my-3">
        @if (Model.TotalPages > 1)
        {
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    @for (var i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                            <a class="page-link" asp-page="./CatManager" asp-route-pageIndex="@i" asp-route-areaId="@Model.AreaId">@i</a>
                        </li>
                    }
                </ul>
            </nav>
        }
    </div>

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/MenuItemManager.cshtml
@page
@model MenuItemManagerModel
@{
    ViewData["Title"] = "MenuItem Manager";
}
<div class="container">
    <h1 class="text-center my-4">MenuItem Manager</h1>

    <!-- Sắp xếp và Tạo mới -->
    <div class="d-flex justify-content-between my-3">
        <div>
            <a asp-page-handler="Sort" asp-route-sortOrder="Address" class="btn btn-link mx-2">Sort </a>
        </div>
        <div>

            <a asp-page="CreateItem" asp-route-shopId="@Model.ShopId" class="btn btn-primary">Create New Item</a>
        </div>
    </div>

    <!-- Tìm kiếm -->
    <form method="get" class="mb-4">
        <div class="input-group">
            <input type="text" name="searchString" class="form-control" placeholder="Search"
            <input type="hidden" name="sortOrder" value="@ViewData["CurrentSort"]" />
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>

    <table class="table table-striped">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Price</th>
                <th>Enabled</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.MenuItems)
            {
                <tr>
                    <td>@item.ItemId</td>
                    <td>@item.ItemName</td>
                    <td>@item.ItemPrice</td>
                    <td>@(item.ItemEnabled ?? false)</td>
                    <td>
                        <form method="post" asp-page-handler="ToggleEnabled" asp-route-id="@item.ItemId" asp-route-isEnabled="@(!item.ItemEnabled)">
                            <button type="submit" class="btn btn-link">@((item.ItemEnabled ?? false) ? "Disable" : "Enable")</button>
                        </form>
                        <!-- Nút Update -->
                        <a asp-page="UpdateItem" asp-route-shopId="@item.ShopId " asp-route-id="@item.ItemId" class="btn btn-link">Update</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a asp-page="./ShopManager" class="btn btn-primary">Back</a>
    <!-- Phân trang -->
    <div class="d-flex justify-content-center my-3">
        @if (Model.TotalPages > 1)
        {
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    @for (var i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                            <a class="page-link" asp-page="./MenuItemManager" asp-route-pageIndex="@i" asp-route-shopId="@Model.ShopId">@i</a>
                        </li>
                    }
                </ul>
            </nav>
        }
    </div>

CoffeeCat/CoffeeCatRazporPage/Pages/ShopOwner/StaffManager.cshtml
@* @page
@model CoffeeCatRazporPage.Pages.ShopOwner.StaffManagerModel
@{
    ViewData["Title"] = "Coffee Shops";
}
<h1>List of Users by Role</h1>
<a asp-page="/ShopOwner/CreateStaff" class="btn btn-primary">Create Staff</a>   
<table>
    <thead>
        <tr>
            <th>Customer ID</th>
            <th>Name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.UserList)
        {
            <tr>
                <td>@user.CustomerId</td>
                <td>@user.CustomerName</td>
                <td>@user.CustomerEmail</td>
                <td width="10%">
                    @if (user.CustomerEnabled == true)
                    {
                        <form method="post" asp-page-handler="Ban">
                            <input type="hidden" name="customerId" value="@user.CustomerId" />
                            <button type="submit" class="btn btn-danger mx-2">
                                Ban
                            </button>
                        </form>
                    }
                    else
                    {
                        <form method="post" asp-page-handler="Unban">
                            <input type="hidden" name="customerId" value="@user.CustomerId" />
                            <button type="submit" class="btn btn-primary mx-2">
                                Unban
                            </button>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table> *@
@page
@model CoffeeCatRazporPage.Pages.ShopOwner.StaffManagerModel
@{
    ViewData["Title"] = "Coffee Shops";
}

<style>
    /* CSS cho bảng */
    .styled-table {
        width: 100%;
        border-collapse: collapse;
        margin: 25px 0;
        font-size: 0.9em;
        font-family: sans-serif;
        border-radius: 10px;
        overflow: hidden;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.15);
    }

        .styled-table thead tr {
            background-color: #009879;
            color: #ffffff;
            text-align: left;
        }

        .styled-table th,
        .styled-table td {
            padding: 12px 15px;
        }

        .styled-table tbody tr {
            border-bottom: 1px solid #dddddd;
        }

            .styled-table tbody tr:nth-of-type(even) {
                background-color: #f3f3f3;
            }

            .styled-table tbody tr:last-of-type {
                border-bottom: 2px solid #009879;
            }

            .styled-table tbody tr.active-row {
                font-weight: bold;
                color: #009879;
            }

    /* CSS cho nút */
    .btn {
        display: inline-block;
        padding: 10px 20px;
        font-size: 16px;
        cursor: pointer;
        text-align: center;
        text-decoration: none;
        outline: none;
        color: #fff;
        background-color: #009879;
        border: none;
        border-radius: 5px;
        box-shadow: 0 5px #00664d;
    }

        .btn:hover {
            background-color: #007366;
        }
</style>

<h1>List of Users by Role</h1>
<a asp-page="/ShopOwner/CreateStaff" class="btn btn-primary">Create Staff</a>

<table class="styled-table">
    <thead>
        <tr>
            <th>Customer ID</th>
            <th>Name</th>
            <th>Email</th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var user in Model.UserList)
        {
            <tr>
                <td>@user.CustomerId</td>
                <td>@user.CustomerName</td>
                <td>@user.CustomerEmail</td>
                <td>
                    @if (user.CustomerEnabled == true)
                    {
                        <form method="post" asp-page-handler="Ban">
                            <input type="hidden" name="customerId" value="@user.CustomerId" />
                            <button type="submit" class="btn btn-danger mx-2">Ban</button>
                        </form>
                    }
                    else
                    {
                        <form method="post" asp-page-handler="Unban">
                            <input type="hidden" name="customerId" value="@user.CustomerId" />
                            <button type="submit" class="btn btn-primary mx-2">Unban</button>
                        </form>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>