CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingForm.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories;

namespace CoffeeCatRazporPage.Pages.Customer {
    public class BookingFormModel : PageModel {
        private readonly ICoffeeShopManagerRepository<Booking> bookingRepository;

        public BookingFormModel(ICoffeeShopManagerRepository<Booking> bookingRepository) {
            this.bookingRepository = bookingRepository;
        }

        [BindProperty]
        public int AreaId { get; set; }
        [BindProperty]
        public int ShopId { get; set; }
        public async Task<IActionResult> OnGetAsync(int? areaId, int? shopId) {
            Authenticate();
            Authorization();

            AreaId = (int)areaId;
            ShopId = (int)shopId;

            return Page();
        }

        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 4) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingHistory.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories;
using Repositories.Auth;


namespace CoffeeCatRazporPage.Pages.Customer {
    public class BookingHistoryModel : PageModel {
        private readonly ICoffeeShopManagerRepository<Booking> bookingRepository;
        private readonly ICoffeeShopStaffRepository repository;
        private readonly ISessionRepository sessionrepository;

        public BookingHistoryModel(ICoffeeShopManagerRepository<Booking> bookingRepository, ISessionRepository sessionrepository, ICoffeeShopStaffRepository repository) {
            this.bookingRepository = bookingRepository;
            this.sessionrepository = sessionrepository;
            this.repository = repository;
        }
        public List<Booking> BookingHistory { get; set; }
        [BindProperty]
        public int bookingId { get; set; }
        public async Task<IActionResult> OnGet() {
            Authenticate();
            Authorization();
            BookingHistory  = await bookingRepository.GetBookingHistoryForCustomerAsync(HttpContext.Session.GetInt32("UserId"));
            return Page();
        }
        public async Task<IActionResult> OnPostCancelBookingAsync(int bookingId)
        {
            var booking = await repository.GetBookingByIdAsync(bookingId);

            if (booking == null)
            {
                return NotFound();
            }

            if (booking.BookingEnabled != false)
            {
                TempData["ErrorMessage"] = "Cannot cancel a booking that is already enabled.";
                return RedirectToPage(); 
            }

            await repository.DeleteAsync(booking);

            return RedirectToPage();
        }

        private void Authenticate()
        {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null)
            {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 4) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingMenuItem.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories;

namespace CoffeeCatRazporPage.Pages.Customer {
    public class BookingMenuItemModel : PageModel {
        private readonly ICoffeeShopManagerRepository<MenuItem> menuItemRepository;

        public BookingMenuItemModel(ICoffeeShopManagerRepository<MenuItem> menuItemRepository) {
            this.menuItemRepository = menuItemRepository;
        }

        [TempData]
        public int BookingId { get; set; }
        [BindProperty]
        public List<int> menuItemIds { get; set; }
        public int ShopId { get; set; }
        public List<MenuItem> MenuItems { get; set; }
        public async Task<IActionResult> OnGetAsync(int bookingId, int shopId) {
            Authenticate();
            Authorization();
            BookingId = bookingId;
            ShopId = shopId;
            MenuItems = await menuItemRepository.GetAllMenuItemByShopIdAsync(shopId);

            return Page();
        }


        public async Task<IActionResult> OnPostAsync() {


            await menuItemRepository.AddMenuItemsToBookingAsync(BookingId, menuItemIds);


            return RedirectToPage("/Customer/BookingHistory");
        }

        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 4) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingSuccess.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace CoffeeCatRazporPage.Pages.Customer {
    public class BookingSuccessModel : PageModel {
        public void OnGet() {
            Authenticate();
            Authorization();
        }

        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 4) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingTable.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Repositories;
using Repositories.Auth;
using System.ComponentModel.DataAnnotations;

namespace CoffeeCatRazporPage.Pages.Customer {
    public class BookingTableModel : PageModel {
        private readonly ICoffeeShopManagerRepository<Table> tableRepository;
        private readonly ICoffeeShopManagerRepository<Booking> bookingRepository;
        private readonly ISessionRepository sessionrepository;

        public BookingTableModel(ICoffeeShopManagerRepository<Table> tableRepository, ICoffeeShopManagerRepository<Booking> bookingRepository, ISessionRepository sessionRepository) {
            this.tableRepository = tableRepository;
            this.bookingRepository = bookingRepository;
            this.sessionrepository = sessionRepository;
        }

        [BindProperty]
        public List<int> TableIds { get; set; }

        [BindProperty]
        public List<Table> SelectedTables { get; set; }

        [BindProperty]
        [Display(Name = "Booking Start Time")]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddTHH:mm}")]
        public DateTime BookingStartTime { get; set; }

        [Display(Name = "Booking End Time")]
        [BindProperty]
        [DataType(DataType.DateTime)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-ddTHH:mm}")]
        public DateTime BookingEndTime { get; set; }

        [BindProperty]
        public List<Table> Tables { get; set; }
        [TempData]
        public int BookingId { get; set; }
        [BindProperty]
        public int AreaId { get; set; }
        [BindProperty]
        public int ShopId { get; set; }
        [BindProperty]
        public bool IsTableSelectionRequired { get; set; }
        public string ErrorMessage { get; set; }
        public async Task<IActionResult> OnGet() {
            Authenticate();
            Authorization();

            IsTableSelectionRequired = true;
            if (Request.Query.TryGetValue("areaId", out var areaId) &&
                Request.Query.TryGetValue("shopId", out var shopId) &&
                Request.Query.TryGetValue("startTime", out var startTime) &&
                Request.Query.TryGetValue("endTime", out var endTime)) {
                AreaId = int.Parse(areaId);
                BookingStartTime = DateTime.Parse(startTime);
                BookingEndTime = DateTime.Parse(endTime);
                ShopId = int.Parse(shopId);

                var availableTables = await bookingRepository.GetAvailableTablesAsync(AreaId, BookingStartTime, BookingEndTime);
                Tables = availableTables.Where(table => table.TableStatus == true && table.TableEnabled == true).ToList();
            }
            if (Tables == null || !Tables.Any())
            {
                ErrorMessage = "Sorry, the table is full.";
                return Page();
            }

            return Page();
        }


        public async Task<IActionResult> OnPostAsync() {
            // Xử lý form booking

            bool areAllTablesAvailable = await CheckAllTablesAvailability(SelectedTables, BookingStartTime, BookingEndTime);
            var customer = sessionrepository.GetUserByRole(HttpContext.Session.GetInt32("UserId"));
            var booking = new Booking {
                BookingCode = GenerateBookingCode(),
                BookingStartTime = BookingStartTime,
                BookingEndTime = BookingEndTime,
                BookingEnabled = false,
                CustomerId = customer.CustomerId
            };

            if (areAllTablesAvailable) {
                await bookingRepository.AddAsync(booking);
                await bookingRepository.AddTablesToBookingAsync(booking.BookingId, TableIds);

                return RedirectToPage("/Customer/BookingMenuItem", new { bookingId = booking.BookingId, shopId = ShopId });
            } else {
                ModelState.AddModelError(string.Empty, "One or more selected tables are not available for the specified date.");
                return Page();
            }
        }
        private string GenerateBookingCode() {
            string code = "BOOK" + DateTime.Now.ToString("yyyyMMddHHmmss");
            return code;
        }

        private async Task<bool> CheckAllTablesAvailability(List<Table> tables, DateTime bookingStartTime, DateTime bookingEndTime) {
            var distinctTables = tables.Distinct().ToList();

            foreach (var table in distinctTables) {
                var existingBooking = await bookingRepository.GetBookingByTableAndTimeAsync(table.TableId, bookingStartTime, bookingEndTime);

                if (existingBooking != null) {
                    table.TableStatus = false;
                    await tableRepository.UpdateAsync(table);
                    return false;
                }
            }

            return true;
        }

        private void Authenticate() {
            int? userId = HttpContext.Session.GetInt32("UserId");

            if (userId == null) {
                HttpContext.Response.Redirect("/Auth/SignIn");
            }
        }

        private void Authorization() {
            int? roleId = HttpContext.Session.GetInt32("RoleId");
            if (roleId.HasValue) {
                if (roleId.Value != 4) {
                    HttpContext.Response.Redirect("/Error/403");
                }
            }
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/DetailCat.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Repositories;

namespace CoffeeCatRazporPage.Pages.Customer
{
    public class DetailCatModel : PageModel
    {
        private readonly ICustomerRepository<Cat> repository;
        private readonly ICustomerRepository<Area> areaRepository;
        public DetailCatModel(ICustomerRepository<Cat> repository, ICustomerRepository<Area> areaRepository)
        {
            this.repository = repository;
            this.areaRepository = areaRepository;
        }
        [BindProperty(SupportsGet = true)]
        public IEnumerable<Cat> Cats { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int AreaId { get; set; }
        public int? ShopId { get; set; }
        public async Task OnGetAsync(int? pageIndex, int AreaId)
        {
            this.AreaId = AreaId;
            IQueryable<Cat> catsQuery = await repository.GetCatEnableAsync();
            var area = await areaRepository.GetShopByIdAsync(AreaId);
            ShopId = area.ShopId;
            catsQuery = catsQuery.Where(a => a.AreaId == this.AreaId);

            int pageSize = 5;
            CurrentPage = pageIndex ?? 1;
            TotalPages = (int)Math.Ceiling(await catsQuery.CountAsync() / (double)pageSize);

            Cats = await catsQuery.Skip((CurrentPage - 1) * pageSize).Take(pageSize).ToListAsync();
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/DetailTable.cshtml.cs
using Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Repositories;

namespace CoffeeCatRazporPage.Pages.Customer
{
    public class DetailTableModel : PageModel
    {
        private readonly ICustomerRepository<Table> repository;
        private readonly ICustomerRepository<Area> areaRepository;
        public DetailTableModel(ICustomerRepository<Table> repository, ICustomerRepository<Area> areaRepository)
        {
            this.repository = repository;
            this.areaRepository = areaRepository;
        }
        [BindProperty(SupportsGet = true)]
        public IEnumerable<Table> Tables { get; set; }
        public int CurrentPage { get; set; }
        public int TotalPages { get; set; }
        public int AreaId { get; set; }
        public int? ShopId { get; set; }
        public async Task OnGetAsync(int? pageIndex, int AreaId)
        {
            this.AreaId = AreaId;
            IQueryable<Table> tablesQuery = await repository.GetTableEnableAsync();
            var area = await areaRepository.GetShopByIdAsync(AreaId);
            ShopId = area.ShopId;
            tablesQuery = tablesQuery.Where(a => a.AreaId == this.AreaId);

            int pageSize = 5;
            CurrentPage = pageIndex ?? 1;
            TotalPages = (int)Math.Ceiling(await tablesQuery.CountAsync() / (double)pageSize);

            Tables = await tablesQuery.Skip((CurrentPage - 1) * pageSize).Take(pageSize).ToListAsync();
        }
    }
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingForm.cshtml
@page
@model BookingFormModel
@{
    ViewData["Title"] = "Booking Form";
}

<h1>Booking Form</h1>

<form method="post">
    <input type="hidden" id="AreaId" name="AreaId" value="@Model.AreaId"> 

    <div class="form-group">
        <label for="BookingStartDate">Booking Start Date:</label>
        <input type="date" class="form-control" id="BookingStartDate" name="BookingStartDate">
    </div>
    <div class="form-group">
        <label for="BookingStartTime">Booking Start Time:</label>
        <select class="form-control" id="BookingStartTime" name="BookingStartTime">
            <option value="07:00">7:00 AM</option>
            <option value="09:00">9:00 AM</option>
            <option value="13:00">1:00 PM</option>
            <option value="15:00">3:00 PM</option>
        </select>
    </div>
    <div class="form-group">
        <label for="BookingEndTime">Booking End Time:</label>
        <select class="form-control" id="BookingEndTime" name="BookingEndTime">
            <option value="09:00">9:00 AM</option>
            <option value="11:00">11:00 AM</option>
            <option value="15:00">3:00 PM</option>
            <option value="17:00">5:00 PM</option>
        </select>
    </div>
    <input type="hidden" name="ShopId" id="ShopId" value="@Model.ShopId">
    <button type="button" class="btn btn-primary" id="checkAvailability">Check Availability</button>
    <a asp-page="./DetailTable" asp-route-AreaId="@Model.AreaId" class="btn btn-primary">Back</a>
</form>

@section Scripts {
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        $(document).ready(function () {
            // Function to update the minimum date for booking start date
            function updateMinDate() {
                var today = new Date().toISOString().split('T')[0];
                $("#BookingStartDate").attr("min", today);
            }

            // Update the minimum date immediately
            updateMinDate();

            $("#checkAvailability").click(function () {
                var areaId = $("#AreaId").val();
                var startDate = $("#BookingStartDate").val();
                var startTime = $("#BookingStartTime").val();
                var endTime = $("#BookingEndTime").val();
                if (startDate === "") {
                    alert("Please select Booking Start Date.");
                    return;
                }
                var fullStartTime = startDate + "T" + startTime;
                var fullEndTime = startDate + "T" + endTime;

                if (new Date(fullStartTime) >= new Date(fullEndTime)) {
                    alert("The end time must be greater than the start time.");
                    return;
                }

                window.location.href = '/Customer/BookingTable?areaId=' + @Model.AreaId + '&shopId=' + @Model.ShopId + '&startTime=' + encodeURIComponent(fullStartTime) + '&endTime=' + encodeURIComponent(fullEndTime);
            });
        });

    </script>
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingHistory.cshtml
@page
@model BookingHistoryModel
@{
    ViewData["Title"] = "Booking History";
}

<h1>Booking History for Customer: </h1>

@if (Model.BookingHistory != null && Model.BookingHistory.Any())
{
    <table class="table">
        <thead>
            <tr>
                <th>Booking Code</th>
                <th>Start Time</th>
                <th>End Time</th>
                <th>Items</th>
                <th>Tables</th>
                <th>Status</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var booking in Model.BookingHistory)
            {
                <tr>
                    <td>@booking.BookingCode</td>
                    <td>@booking.BookingStartTime</td>
                    <td>@booking.BookingEndTime</td>
                    <td>
                        <ul>
                            @foreach (var item in booking.Items)
                            {
                                <li>item name: @item.ItemName - price: @item.ItemPrice vnđ</li>
                            }
                        </ul>
                    </td>
                    <td>
                        <ul>
                            @foreach (var table in booking.Tables)
                            {
                                <li>table: @table.TableName - capacity:@table.TableCapacity</li>
                            }
                        </ul>
                    </td>
                    <td>@(booking.BookingEnabled == true ? "Enabled" : "Disabled")</td>
                    <td>
                        @if (booking.BookingEnabled == false)
                        {
                            <form method="post" asp-page-handler="CancelBooking" asp-route-bookingId="@booking.BookingId">
                                <button type="submit" class="btn btn-danger">Cancel Booking</button>
                            </form>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingMenuItem.cshtml
@page
@model BookingMenuItemModel
@{
    ViewData["Title"] = "Booking Menu Items";
}

<h1>Booking Menu Items</h1>

<form method="post">
    <input type="hidden" asp-for="BookingId" />
    <input type="hidden" asp-for="ShopId" /> 

    <div class="form-group">
        <label for="menuItemIds">Select Menu Items:</label>
        <select multiple class="form-control" id="menuItemIds" asp-for="menuItemIds">
            @foreach (var menuItem in Model.MenuItems)
            {
                <option value="@menuItem.ItemId">@menuItem.ItemName: @menuItem.ItemPrice vnđ</option>
            }
        </select>
    </div>

    <button type="submit" class="btn btn-primary">Confirm</button>
</form>

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingSuccess.cshtml
@page
@model BookingSuccessModel
@{
    ViewData["Title"] = "Booking Success";
}

<h1>Booking Successful!</h1>

<p>Your booking has been successfully placed.</p>

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/BookingTable.cshtml
 @page
@model BookingTableModel
@{
    ViewData["Title"] = "Booking";
}

<h1>Booking</h1>

<form method="post" onsubmit="return validateForm()">
    @if (Model.IsTableSelectionRequired && Model.Tables != null && Model.Tables.Any())
    {
        <div class="form-group">
            <label for="TableIds">Select Tables:</label>
            <select multiple class="form-control" id="TableIds" asp-for="TableIds">
                @foreach (var table in Model.Tables)
                {
                    <option value="@table.TableId">table: @table.TableName    capacity: @table.TableCapacity</option>
                }
            </select>
        </div>
    }

    <div class="form-group">
        <label for="BookingStartTime">Booking Start Time:</label>
        <input type="datetime-local" class="form-control" id="BookingStartTime" asp-for="BookingStartTime" asp-format="{0:yyyy-MM-ddTHH:mm}" readonly>
    </div>
    <div class="form-group">
        <label for="BookingEndTime">Booking End Time:</label>
        <input type="datetime-local" class="form-control" id="BookingEndTime" asp-for="BookingEndTime" asp-format="{0:yyyy-MM-ddTHH:mm}" readonly>
    </div>
    <input type="hidden" id="AreaId" name="AreaId">
    <button type="submit" class="btn btn-primary">Book</button>
    <a asp-page="./BookingForm" asp-route-AreaId="@Model.AreaId" asp-route-ShopId="@Model.ShopId" class="btn btn-primary">Back</a>
</form>

@section Scripts {
    <script>
        // Lấy areaId từ URL
        const urlParams = new URLSearchParams(window.location.search);
        const areaId = urlParams.get('areaId');

        
        document.getElementById('AreaId').value = areaId;

      
        function validateForm() {
            
            const selectedTables = document.getElementById('TableIds').selectedOptions;
            if (selectedTables.length === 0) {
                alert('Please select at least one table.');
                return false; 
            }

            return true; 
        }
        var errorMessage = '@Model.ErrorMessage';
        if (errorMessage !== '') {
            alert(errorMessage);
            window.location.href = '/Customer/BookingForm?areaId=@Model.AreaId&shopId=@Model.ShopId';
        }
    </script>
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/CustomerHomePage.cshtml
@page
@model CustomerModel
@{

<div class="container">
    <h1 class="text-center my-4">Coffee Shops</h1>

    <!-- Sắp xếp và Tạo mới -->
    <div class="d-flex justify-content-between my-3">
        <div>
            <a asp-page-handler="Sort" asp-route-sortOrder="Name" class="btn btn-link mx-2">Sort by Name</a>
            <a asp-page-handler="Sort" asp-route-sortOrder="Address" class="btn btn-link mx-2">Sort by Address</a>
        </div>
    </div>

    <!-- Tìm kiếm -->
    <form method="get" class="mb-4">
        <div class="input-group">
            <input type="text" name="searchString" class="form-control" placeholder="Search">
            <!-- Thêm trường sortOrder vào form tìm kiếm -->
            <input type="hidden" name="sortOrder" value="@ViewData["CurrentSort"]" />
            <div class="input-group-append">
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        </div>
    </form>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Address</th>
                <th>Telephone</th>
                <th>Image</th>
                <th>Menu</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var shop in Model.Shops)
            {
                <tr>

                        <td><a asp-page="DetailArea" asp-route-shopId="@shop.ShopId">@shop.ShopName</a></td>
                        <td>@shop.ShopEmail</td>
                        <td>@shop.ShopAddress</td>
                        <td>@shop.ShopTelephone</td>
                        <td>@shop.ShopImage</td>
                        <td><a asp-page="DetailMenu" asp-route-shopId="@shop.ShopId">@shop.ShopName Menu</a></td>
                </tr>
            }
        </tbody>
    </table>
    <!-- Phân trang -->
    <div class="d-flex justify-content-center my-3">
        @if (Model.TotalPages > 1)
        {
            <nav aria-label="Page navigation">
                <ul class="pagination">
                    @for (var i = 1; i <= Model.TotalPages; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                            <a class="page-link" asp-page="" asp-route-pageIndex="@i">@i</a>
                        </li>
                    }
                </ul>
            </nav>
        }
    </div>
</div>
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/DetailArea.cshtml
@page
@model DetailAreaModel

@{

    <div class="container">
        <h1 class="text-center my-4">Areas</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Area Name</th>
                    <th>List</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var area in Model.Areas)
                {
                    <tr>
                        <td>@area.AreaName</td>
                        <td>
                            <select onchange="window.location.href=this.value;">
                                <option selected disabled>Choose...</option>
                                <option value="@Url.Page("DetailTable", new { AreaId = @area.AreaId })">Table</option>
                                <option value="@Url.Page("DetailCat", new { AreaId = @area.AreaId })">Cat</option>
                            </select>
                        </td>
                    </tr>
                }

        </table>
        <!-- Phân trang -->
        <div class="d-flex justify-content-center my-3">
            @if (Model.TotalPages > 1)
            {
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        @for (var i = 1; i <= Model.TotalPages; i++)
                        {
                            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                                <a class="page-link" asp-page="./DetailArea" asp-route-pageIndex="@i" asp-route-shopId="@Model.ShopId">@i</a>
                            </li>
                        }
                    </ul>
                </nav>
            }
        </div>
        <a asp-page="./CustomerHomePage" class="btn btn-primary">Back</a>
    </div>
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/DetailCat.cshtml
@page
@model DetailCatModel
@{

    <div class="container">
        <h1 class="text-center my-4">Cats</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Image</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var cat in Model.Cats)
                {
                    <tr>

                        <td>@cat.CatName</td>
                        <td>@cat.CatImage</td>
                    </tr>
                }
            </tbody>
        </table>
        <a asp-page="./DetailArea" asp-route-ShopId="@Model.ShopId" class="btn btn-primary">Back</a>
        <!-- Phân trang -->
        <div class="d-flex justify-content-center my-3">
            @if (Model.TotalPages > 1)
            {
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        @for (var i = 1; i <= Model.TotalPages; i++)
                        {
                            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                                <a class="page-link" asp-page="" asp-route-pageIndex="@i">@i</a>
                            </li>
                        }
                    </ul>
                </nav>
            }
        </div>
    </div>
}

CoffeeCat/CoffeeCatRazporPage/Pages/Customer/DetailMenu.cshtml
@page
@model DetailMenuModel
@{
    <div class="container">
        <h1 class="text-center my-4">Detail Menu</h1>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price</th>
            </thead>
            <tbody>
                @foreach (var menu in Model.MenuItems)
                {
                    <tr>
                        <td>@menu.ItemName</td>
                        <td>@menu.ItemPrice</td>
                    </tr>
                }
            </tbody>
        </table>
        <!-- Phân trang -->
        <div class="d-flex justify-content-center my-3">
            @if (Model.TotalPages > 1)
            {
                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        @for (var i = 1; i <= Model.TotalPages; i++)
                        {
                            <li class="page-item @(i == Model.CurrentPage ? "active" : "")">
                                <a class="page-link" asp-page="./DetailMenu" asp-route-pageIndex="@i" asp-route-shopId="@Model.ShopId">@i</a>
                            </li>
                        }
                    </ul>
                </nav>
            }
        </div>
    </div>
}